# specifies pid values for joints
gazebo_ros_control/pid_gains:
  joint_x: {p: 5000.0, i: 0.1, d: 10}
  joint_y: {p: 3000.0, i: 0.1, d: 8}
  player_joint_x: {p: 10000.0, i: 0.1, d: 8}
  player_joint_y: {p: 5000.0, i: 0.1, d: 8}
